### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by brrock** [brrock/myos#1]
# MYOS roadmap
## Include a basic Tool chain
- [ ] option to add apk and brew pkg managers
- [ ]  Will ship with bash, curl and glibc.
 ## Other things 
- [ ] switch to bash shell
- [ ] Mabye generate an ISO
- [ ] Get a good name
